#cloud-config
ssh_authorized_keys:
%{ for _ in ssh_authorized_keys }
  - ${_}
%{ endfor }

locale: "en_US.UTF-8"
timezone: "America/New_York"

packages:
  - nano
  - net-tools
  - bash
  - jq

users:
  - default
  - name: rke2
    homedir: /var/lib/rancher/rke2
    system: true
    sudo: ALL=(ALL) NOPASSWD:ALL    
    groups: users, admin
    lock_passwd: false

run-cmd:
  - ${cluster_registration}